### ISSUE TITLE
Can only send but not receive messages.

### ISSUE THREAD

**Issue by InfestedHydra** [EionRobb/purple-discord#49] opened 2017-06-03 17:35 UTC
Sometimes Pidgin ceases to receive anything, debug logs completely quiet, but it will still successfully send messages typed to pidgin to discord.
Disabling and re-enabling the account eventually fixes it.

**Comment by bobbybee** [comment] 2017-08-13 07:15
Closing as the issue is old and it seems nobody has been able to reproduce this? Please reopen if this is still an issue.

**Closed by bobbybee** 2017-08-13 07:15 UTC
