### ISSUE TITLE
Buddy information stopped working

### ISSUE THREAD

**Issue by alexolog** [EionRobb/purple-discord#185] opened 2018-05-20 03:36 UTC
Both ctrl-O in a chat and right-click / Get Info on a buddy in the list display "Information: Retrieving..." which does not resolve.

**Comment by bobbybee** [comment] 2018-05-20 03:37
I cannot reproduce this on Debian buster.

**Comment by alexolog** [comment] 2018-05-20 03:39
Happens on Windows 10

**Comment by alexolog** [comment] 2018-05-20 03:49
Nothing suspicious in the log

**Comment by EionRobb** [comment] 2018-05-20 03:57
Which log is that? Can you attach?

**Comment by alexolog** [comment] 2018-05-20 04:17
The debug window, and I'd rather not since it contains information that I consider to be private

**Comment by andreygursky** [comment] 2018-06-01 03:35
This should be fixed by https://github.com/EionRobb/purple-discord/pull/188.

**Comment by EionRobb** [comment] 2018-06-01 03:44
Oh, good point, @andreygursky 
@alexolog  can you try grabbing a new dll from https://eion.robbmob.com/libdiscord.dll and try again?

**Comment by alexolog** [comment] 2018-06-01 14:56
Works perfectly!  Thank you!

**Closed** 2018-06-02 01:35 UTC
