### ISSUE TITLE
Edited message

### ISSUE THREAD

**Issue by Quelling** [EionRobb/purple-discord#63] opened 2017-07-03 13:01 UTC
After edit message it is does not see that it has been edited.

For example **_purple_-skypeweb** can do it. Look at this https://i.imgur.com/q9rt0B4.png This is only a proposal. I hope you add.

**Comment by bobbybee** [comment] 2017-08-12 23:15
Duplicate of #46

**Closed by bobbybee** 2017-08-12 23:15 UTC
