### ISSUE TITLE
Adium support

### ISSUE THREAD

**Issue by trvrplk** [EionRobb/purple-discord#299] opened 2020-07-09 15:22 UTC
Are there any plans to bundle this for Adium? From what I can tell it isn't too difficult as long as you have a Mac (although it seems most people contributing don't have one), but I have no Objective-C experience so I can't do it myself.

**Comment by RobFog** [comment] 2021-03-09 15:47
Duplicate of #280?

**Comment by EionRobb** [comment] 2021-03-09 20:45
Yup, thanks @RobFog :)

**Closed by EionRobb** 2021-03-09 20:45 UTC
