### ISSUE TITLE
Offline messages

### ISSUE THREAD

**Issue by EionRobb** [EionRobb/purple-discord#4] opened 2017-04-18 07:41 UTC
(inb4 @rdvl97)

**Comment by maxtros** [comment] 2017-05-11 15:55
confirmed...right now its a little annoying using chat rooms...every time you open pidgin you have to always open oficial discord app to see the messages that has been sended between other participants while you were offline

**Comment by EionRobb** [comment] 2017-05-21 09:39
Got this going for group-chats/channels at the moment, but not for one-to-one IM's

**Comment by maxtros** [comment] 2017-05-22 13:58
great news! I'm going to be playing with this and tell you the results. Thanks Eion!!

**Comment by maxtros** [comment] 2017-05-22 17:13
Mnn maybe its too soon but It doesnt seems to be working using lastest .dll...I tried with two accounts on the same room...I log out account "A" and then chat using "B" account...when I log account "A" again...I dont recieve any message...requires some special option?

**Comment by maxtros** [comment] 2017-06-03 22:41
Confirmed...its not working on lastest .dll. Thanks

**Comment by bobbybee** [comment] 2017-06-07 03:58
#52 solves this for DMs and *almost* solves it for rooms.

**Comment by maxtros** [comment] 2017-06-13 16:36
for DMs its working great, thanks! (only this bug i found https://github.com/EionRobb/purple-discord/issues/57) ...but form rooms it seems not working at all. Thanks bobby!

**Comment by bobbybee** [comment] 2017-08-11 01:58
Closing in favour of more specific issues #24 and #57

**Closed by bobbybee** 2017-08-11 01:58 UTC
