### ISSUE TITLE
Inaccessible rooms are fetched in room list

### ISSUE THREAD

**Issue by zergling-man** [EionRobb/purple-discord#61] opened 2017-06-17 00:43 UTC
I can see all the secret channels; I haven't tried to join any yet.

**Comment by EionRobb** [comment] 2017-06-17 01:19
You can "join" them in Pidgin, but you can't send or receive messages in them.

Unfortunately there's not much we can do about this as that's what the Discord servers send us.  (they also send through the topics of the private rooms, which a lot of people assume to be secure)

**Comment by bobbybee** [comment] 2017-08-11 06:38
Duplicate of #45

**Closed by bobbybee** 2017-08-11 06:38 UTC
