### ISSUE TITLE
Joining A group channel shows wrong partecipants

### ISSUE THREAD

**Issue by Penaz91** [EionRobb/purple-discord#37] opened 2017-05-16 17:52 UTC
Using commit 9b42bb6, I noticed that joining a group shows all the online people on the discord server, times 3, instead of showing the online participants in the room.

Let me try to explain:

Server has 3 people online: A, B and me
Me and B are part of the "offtopic" room, so the user list should show 2 people in the room: "me" and "B".

Instead it shows 9 people online: A A A B B B Me Me Me.

Attaching the real-life example:

![screen](https://cloud.githubusercontent.com/assets/6682630/26120415/faa16948-3a70-11e7-950f-65be513e8225.png)

None of the blurred people should show, and then there's the triple me.

This happens with every room I join.

As for the rest, everything works great, I can send and receive messages correctly.

**Comment by Penaz91** [comment] 2017-05-16 18:46
The triple people seem to disappear after a while (probably someone logged on while i was away?) but the people that shouldn't be in the channel keep showing

**Comment by bobbybee** [comment] 2017-08-11 06:36
Duplicate of #16

**Closed by bobbybee** 2017-08-11 06:36 UTC
