### ISSUE TITLE
Sending URLs containing certian symbols break due to auto / formatting

### ISSUE THREAD

**Issue by SoraHjort** [EionRobb/purple-discord#65] opened 2017-07-14 21:01 UTC
when I send a link through chat that contains certain symbols, like the underscore, it'll automatically put a / in it, thus breaking it.
Example link: https://www.youtube.com/watch?v=NpTaQKX_j8g 
comes out to everyone else as: https://www.youtube.com/watch?v=NpTaQKX/_j8g

So two requests related to it
1. Have urls be an exception to the automatic formatting
2. have the ability to disable automatic exit formatting in the account settings.

**Comment by bobbybee** [comment] 2017-07-14 21:04
Duplicate of #55

**Comment by SoraHjort** [comment] 2017-07-14 22:00
Ahh that's why I didn't see that it was a duplicate. The title wasn't referring to urls specifically.

**Comment by bobbybee** [comment] 2017-08-11 03:57
(Closing as a duplicate)

**Closed by bobbybee** 2017-08-11 03:57 UTC
