### ISSUE TITLE
Unable to add chat rooms (lastest .dll)

### ISSUE THREAD

**Issue by maxtros** [EionRobb/purple-discord#34] opened 2017-05-15 02:15 UTC
Using the lastest .dll when you try to add a chat rooms to you buddie list its added as "(null)" chat room and you can't enter on it from the buddie list.

**Comment by EionRobb** [comment] 2017-05-15 03:06
What steps are you taking to add it to the buddy list (there's a few different ways)?

**Comment by maxtros** [comment] 2017-05-15 16:28
Hi Eion "Tools" -> "Room Lists" or something like that...in spanish its "Herramientas "->"Lista de salas". Thanks!

**Comment by EionRobb** [comment] 2017-05-15 21:15
And then are you choosing the "Join" button or the "Add" button?

**Comment by maxtros** [comment] 2017-05-16 17:47
Add...if i chose Join it joins and chat works....the problem its when I add it.

**Comment by EionRobb** [comment] 2017-05-21 09:39
Sorry for the delay getting to fix this one.  Can you try with the latest dll and see if it works for you?

**Comment by maxtros** [comment] 2017-05-22 13:25
Tested with lastest .dll and Now its partially working but now it has a few new bugs:

1) Rooms Names are missing when you add it to your buddies list now a number as name like "2646823112312" or something like that. On Conversation window and Room list windows it shows the right name but not on Buddy List.
2) Contacts are missing on buddy list...Only real contacts/buddies are missing, Rooms/Channels are there but with the bug "1".

**Comment by bobbybee** [comment] 2017-06-08 03:35
Duplicate of focused #53 

Please close.

**Comment by EionRobb** [comment] 2017-06-10 09:02
Closing as dup

**Closed by EionRobb** 2017-06-10 09:02 UTC
