### ISSUE TITLE
User name/discriminator changes aren't reflected

### ISSUE THREAD

**Issue by EionRobb** [EionRobb/purple-discord#199] opened 2018-08-15 04:42 UTC
If a user changes their username or discriminator (number suffix thing) in discord, they appear as a new user in Pidgin, in the Discord group, rather than having the existing buddy renamed to match

This needs to be checked in two places:
* during login
* during user updated event

**Comment by bobbybee** [comment] 2018-08-15 14:33
I can confirm this happening (a friend of mine changed her nick, way
back when)

**Comment by bobbybee** [comment] 2018-11-30 07:02
Duplicate of #70

**Closed by bobbybee** 2018-11-30 07:02 UTC
